### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by mfeineis** [canapea/canapea#66]
Tried setting up benchmarks using `iai` in but wouldn't work on macOS and also panicked in CI

```toml

[dev-dependencies]
# criterion.rs "mini" for checks in CI environments
iai = { version = "0.1" }

[[bench]]
name = "traversal"
harness = false

```

```rust
#[doc(hidden)]
#[doc = r"Only exposed for benchmarks"]
```

```rust
extern crate canapea_semantic_analyzer;

// FIXME: criterion.rs/iai.rs need a public interface and have their own
//        test harness due to being compiled into separate crate.
// See: https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html
// And: https://github.com/rust-lang/rust/issues/50297

use iai::black_box;

use std::fs::File;
use std::io::Read;

use canapea_semantic_analyzer::{
    create_parser,
    traverse::{Order, traverse_tree},
};

type TreeSitterTree = tree_sitter::Tree;

fn dogfood() -> TreeSitterTree {
    let mut parser = create_parser();

    let mut file = File::open("../../org.canapea.core/src/lang.cnp")
        .expect("../../org.canapea.core/src/lang.cnp should exist");
    let mut code = String::new();
    file.read_to_string(&mut code).unwrap();

    return parser
        .parse(code, None)
        .expect("Error parsing provided code");
}

fn dogfooding_preorder() {
    let tree = black_box(dogfood());

    let _ = traverse_tree(&tree, Order::Pre).collect::<Vec<_>>();
}

fn dogfooding_postorder() {
    let tree = black_box(dogfood());

    let _ = traverse_tree(&tree, Order::Post).collect::<Vec<_>>();
}

iai::main!(dogfooding_preorder, dogfooding_postorder);
```

```yaml
  benchmarks:
    name: Benchmark CLI
    defaults:
      run:
        # Only applies to "run" commands in steps
        working-directory: ./cli
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        # Benches only run on unix due to valgrind dependency
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |-
          sudo apt-get install -y build-essential valgrind
      - run: rustup --version
      - name: Run benches in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo bench --verbose
```
